export const INCREASE_PRODUCT_AMOUNT = 'products/INCREASE_PRODUCT_AMOUNT';
export const DECREASE_PRODUCT_AMOUNT = 'products/DECREASE_PRODUCT_AMOUNT';
export const SET_PRODUCT_AMOUNT = 'products/SET_PRODUCT_AMOUNT';